tools:
  # we want to use a pinned version of binny to manage the toolchain (so binny manages itself!)
  - name: binny
    version:
      want: v0.9.0
    method: github-release
    with:
      repo: anchore/binny

  # used for linting
  - name: golangci-lint
    version:
      want: v2.4.0
    method: github-release
    with:
      repo: golangci/golangci-lint

  # used to release all artifacts
  - name: goreleaser
    version:
      want: v2.12.0
    method: github-release
    with:
      repo: goreleaser/goreleaser


  # used for running all local and CI tasks
  - name: task
    version:
      want: v3.44.1
    method: github-release
    with:
      repo: go-task/task
